### ISSUE TITLE
Issues with 'az network dns zone update'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1123]
Issues with 'az network dns zone update':
- [x] -h help text has two groups of parameters both under the same heading 'Generic Update Arguments'.  These should be grouped into a single group, containing add/remove/set (Fixed #1015)
- [ ] ~~Not clear how add/remove/set should be used.  For example, how do I add, edit or remove ARM Tags using this command?  Needs concrete examples.~~ (Tracked by #1582)
- [x] Supporting If-none-match is pointless, it's only useful when creating zones, and that should be done via 'az network dns zone create'.  We should support the option to control create-if-not-exist there, not here. (PR #1300)

**Comment by JasonRShaver** [comment]
* remove if-none-match
* add examples

**Comment by jtuliani** [comment]
For zone update, please add example of ARM tag create/update/remove

**Comment by jtuliani** [comment]
For tags, we need examples covering:
 - Removing all tags
 - Adding a new tag (suggest using "dept=finance")
 - Removing an existing tag, leaving other items in place (again, use "dept=finance")

**Comment by tjprescott** [comment]
Reopening since the PR only addressed part of this issue.

**Comment by tjprescott** [comment]
Points 1 and 3 have been fixed. Point 2 is a more general issue with generic update that does not pertain specially to DNS so it is being tracked as a separate issue.
