### ISSUE TITLE
Issues with 'az network dns record-set create'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1129]
Issues with 'az network dns record-set create':
- [x] 1. No description in command (and no description in 'az network dns record-set -h').  Suggest "Create an empty record set in a DNS zone." (PR #1129)
- [x] 2. --zone-name is a mandatory parameter.  People will need to type this a lot.  It needs a short format, I suggest '-z' (PR #1129)
- [x] 3. --type: similarly it would be good to support this as --type -t (PR #1129)
- [x] 4. For --type, you cannot create a SOA record (they're created for you with the zone).  The SOA value is a valid entry in the record type enum, but not supported in this context.  The Help text should reflect this. (PR #1129)
- [x] 5. No support for metadata.  This is a bit like tags on zones (name-value pairs).  Needs to be supported. (PR #1129)
- [x] 6. No support for concurrency.  As with zone create, should support defensive scripting against concurrent operations, e.g. via if-none-match \* to prevent overwriting existing record sets. (PR #1129)

**Comment by JasonRShaver** [comment]
* add short summary, example, long summary?
* add -z, -t

Discuss:
What is the usage or scenario for metadata.
Example of concurrency scenario (otherwise add if-none-match)

**Comment by jtuliani** [comment]
As discussed: metadata is like tags, just doesn't support full ARM tag functionality hence different name.  Agreed to support metadata via add/remove rather than at create time.

Will file separate bug for if-none-match

**Comment by jtuliani** [comment]
Re number 6 above...support concurrency via if-match and if-none-match explicitly (both are applicable for this command).
