### ISSUE TITLE
Issues with 'az network dns record-set list'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1131]
Issues with 'az network dns record-set list'
- [x] 1. As with 'create' and 'delete', should support -z as short form for --zone-name (PR #1129)
- [ ] 2a. <del>No way to format results as table whilst still showing record values (RDATA). </del> _This will require a change to our output infrastructure and is being tracked by item #1948_
- [x] 2b. Also, the record type is not shown. This is a serious regression relative to the old CLI and makes the list output useless. (PR #1823).
- [x] 3. Doesn't show metadata in table format either (PR #1823)
- [x] 4. JSON output should not show 'null' output for each record type that doesn't apply to the record being listed.  Instead, these lines should be suppressed. (PR #1592)
- [x] 5. Doesn't support --type for listing record sets of a specific type only.  This is a regression vs old CLI. (PR #1823)
- [x] 6. Remove --top parameter.  Where results include a NextLink, this should be followed and each page of results returned. (PR #1823)

**Comment by JasonRShaver** [comment]
* short names
* correct table output (does service return this?) (#2, #3)
* Filtering by type (assuming service supports) 
* remove top

**Comment by jtuliani** [comment]
Sample output attached
[Sample record set list.txt](https://github.com/Azure/azure-cli/files/572078/Sample.record.set.list.txt)

**Comment by jtuliani** [comment]
Also attaching example of current output...you can see all the 'null' items listed, which are a problem as described in item 4 above.
[Existing record-set list output.txt](https://github.com/Azure/azure-cli/files/572135/Existing.record-set.list.output.txt)

**Comment by jtuliani** [comment]
As discussed...JSON output over the wire does not include 'null' items, so they should definitely not be in the CLI JSON format.  Re formatted sample output, @JasonRShaver to investigate

**Comment by tjprescott** [comment]
The null values exist because msrest deserializes the response into the strongly typed object. Since the values aren't included in the response, they end up as null values in the resulting object. We can handle this with a transform of the output.
