### ISSUE TITLE
Issues with 'az network dns record-set show'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1132]
Issues with 'az network dns record-set show':
- [ ] ~~1. If record set does not exist, error message says The resource record 'cccnamed' does not exist in resource group 'rg1' of subscription '<id>'.  This error also needs to list the zone name.~~
- [x] 2. In some cases (e.g. showing the SOA at the zone apex via az network dns record-set show -g rg1 -n "@" --type SOA --zone-name jt-test.com), I just get a red message 'Failed to open file' and no record set is shown (PR #1581)
- [x] 3. When showing, do not include all the 'null' objects for other record types in the JSON output. (#1592)
- [x] 4. Needs short form for --zone-name (-z) and --type (-t) (PR #1129)

**Comment by JasonRShaver** [comment]
* add zone name to error (does service return zone name?)
* add support for DNS-style @ sign
* add -z and -t

service returns nulls for #3, how do we know what to filter?  Is service side filtering a possibliity

**Comment by jtuliani** [comment]
See #1131 for example of current record set output format, plus desired record set output format.

**Comment by tjprescott** [comment]
IRT item 1, this is the error returned from the service. If it is inadequate, it should be updated there.

**Comment by jtuliani** [comment]
Re #1, yes, I believe we already have a service bug for this, good point.
