### ISSUE TITLE
Issues with 'az network dns record-set update'

### ISSUE THREAD

**Issue by jtuliani** [Azure/azure-cli#1133]
Issues with 'az network dns record-set update':
- [ ] 1. ~~As with zone update, the command should support update operations only.  The 'if-none-match' property should therefore not be exposed.~~ (_should be removed from Swagger/SDK if N/A_)
- [x] 2. As with zone update, the two command groups under '--help' both named 'Generic Update Arguments' should be merged. (PR #1015)
- [x] 3. Again under '--help' there needs to be a description.  Also under 'az network dns record-set -h' (PR #1583)
- [x] 4. --zone-name and --type should accept short form (-z and -t) (PR #1583)
- [x] 5. No way to update metadata on record sets (PR #1592)
- [ ] 6. ~~Completely unclear how --add / --remove / --set should be used.  And given the separate commands for adding and removing records, even the presence of these commands is very confusing indeed.  Is there any way these commands can be used to add/remove/update records?~~ Tracked more generally in #1582

**Comment by JasonRShaver** [comment]
* remove if-none-match
* add short summary
* add examples section
* add -z and -t


Discuss generic update and arugments section
Discuss adding metadata with --add

**Comment by jtuliani** [comment]
For metadata, we need examples covering:
 - Removing all metadata
 - Adding a new metadata item (suggest using "dept=finance")
 - Removing an existing metadata item, leaving other items in place (again, use "dept=finance")

**Comment by tjprescott** [comment]
@jtuliani  IRT #1, the DNS SDK is unique in that it actually has a patch operation for a pure update (although we leverage the create_or_update), but even that exposes `if_none_match`.
