### ISSUE TITLE
Support Python 3.10

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#19857]
## Description

Python 3.10 has been released on 2021-10-04: https://www.python.org/downloads/

Azure CLI needs to support Python 3.10 like how we supported 3.9 (https://github.com/Azure/azure-cli/issues/16611).

## TODOs

- [x] [Knack](https://github.com/microsoft/knack) supports Python 3.10: https://github.com/microsoft/knack/pull/250
- [x] [azdev](https://github.com/Azure/azure-cli-dev-tools) supports Python 3.10: https://github.com/Azure/azure-cli-dev-tools/pull/319
- [x] CI passes with Python 3.10
  - [x] Dependencies like `pytest`, `pylint` are updated to the Python 3.10 compatible version: https://github.com/Azure/azure-cli/pull/20192
  - [x] New `pylint` check failures are fixed or ignored: https://github.com/Azure/azure-cli/pull/20192
  - [x] All test cases pass: https://github.com/Azure/azure-cli/pull/20195

**Comment by yonzhan** [comment]
Python 3.10 support

**Comment by miqm** [comment]
@jiasli - will the Docker image be upgraded to python 3.10.x? currently is 3.9.6 (which is not the latest one though)

**Comment by jiasli** [comment]
@miqm, actually we use Python 3.8 in DEB package and Windows MSI, and Python 3.6 in RPM. 😅

Are there any absolute needs to use Python 3.10 in the docker image? I can certainly prioritize it if they are reasonable.

**Comment by miqm** [comment]
@jiasli - It's not a must, however often people use the CLI image in CI/CD systems and some new custom-made scripts might benefit from newer python features.

In general it would be awesome if you produce a series of azure-cli docker tags so people could choose which kind of base image they would like to use (i.e. python3.9-slim-bullseye, python3.8-alpine, etc.)

**Comment by jiasli** [comment]
@miqm, this is a good suggestion. I have created https://github.com/Azure/azure-cli/issues/21074 to track it.

**Comment by jiasli** [comment]
@miqm, upgrade to Python 3.10 in https://github.com/Azure/azure-cli/pull/21079.
