### ISSUE TITLE
[Network] Remove dependencies on external storage account

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#2198]
In order to support Profiles, the following create commands need to be converted to use either SDK calls or dynamic template generation.

**Template Based**
- [x] Application Gateway (PR #2668)
- [x] Load Balancer (PR #2668)

**SDK Based**
- [x] Express Route Circuit (PR #2371)
- [x] Local Gateway (PR #2371)
- [x] NIC (PR #2371)
- [x] NSG (PR #2371)
- [x] Public IP (PR #2294)
- [x] Traffic Manager Profile (PR #2371)
- [x] VNET (PR #2269)
- [x] VNET Gateway (PR #2371)

**Comment by derekbekoe** [comment]
This item needs to be done as part of https://github.com/Azure/azure-cli/issues/2199
