### ISSUE TITLE
Python 3.11 compatibility metabug

### ISSUE THREAD

**Issue by mdboom** [Azure/azure-cli#24119]
Python 3.11 has significant performance improvements over 3.10, and it would be great if Azure CLI could take advantage of those.

Getting Azure CLI compatible with Python 3.11 will require coordinating a few tasks among a number of repos, both internal and external.  I'm creating this metabug to keep track of them.  The checklist below will be updated as I discover more things.

(I'm on the CPython Performance Team at Microsoft which is responsible for a number of these improvements. I am happy to contribute to this effort -- please let me know how I can be most useful fitting into your workflows, etc.)

- [ ] #24109
- [ ] Uses of `inspect.getargspec`
  - [ ] In azure-cli: #24111 
  - [ ] In azure-cli-extensions
  - [ ] In azure-sdk-for-python
- [ ] Upgrade wrapt to >= 1.14, which requires upgrading pylint >= 2.16 (not yet released) in azdev
- [ ] Adapt to `Enum.__str__` changes

**Comment by yonzhan** [comment]
@jiasli for awareness

**Comment by joancafom** [comment]
I came across this issue and would also like to highlight the importance of Python `3.11`. Till this date, the [documentation](https://github.com/Azure/azure-cli/blob/dev/doc/install_linux_prerequisites.md#linux-install-prerequisites) states that the only officially supported Python versions are `3.8` through `3.10`. Don't know if this is still the case though, as there are references to Python 3.11 in the repo.

Some recent vulnerabilities affecting Python have been published and most of them are fixed in more recent versions of the language (for instance: [CVE-2023-36632](https://nvd.nist.gov/vuln/detail/CVE-2023-36632) and [CVE-2023-27043](https://nvd.nist.gov/vuln/detail/CVE-2023-27043)).

As per documentation, Python 3.11 does not seem to be supported, I would very much appreciate an statement on whether these vulnerabilities affect the project or not. 

Thanks in advance!

**Comment by luckman212** [comment]
@joancafom As of `az` 2.54.0, Python 3.11 is supported.

**Comment by joancafom** [comment]
Neat! Thanks for pointing out

**Comment by yonzhan** [comment]
We now support Python 3.13 in Azure CLI.
