### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-cli#24494]
## Description

Python 3.11 has been released on 2022-10-24: https://www.python.org/downloads/release/python-3110/

Azure CLI needs to support Python 3.11 like how we supported 3.9 (https://github.com/Azure/azure-cli/issues/16611), 3.10 (https://github.com/Azure/azure-cli/issues/19857).

## TODOs

- [ ] [Knack](https://github.com/microsoft/knack) supports Python 3.11
  - https://github.com/microsoft/knack/pull/275
- [ ] [azdev](https://github.com/Azure/azure-cli-dev-tools) supports Python 3.11
  - `pylint` (https://github.com/Azure/azure-cli-dev-tools/pull/359)
  - `vcrpy` (same as above)
- [ ] Dependencies are updated to the Python 3.11 compatible version
  - `psycopg2` (https://github.com/Azure/azure-cli/pull/24671)
  - `pywin32` (https://github.com/Azure/azure-cli/pull/24982)
  - `cffi` `psutil` (https://github.com/Azure/azure-cli/pull/26842)
- [ ] CI passes with Python 3.11
  - https://github.com/Azure/azure-cli/pull/24497
  - https://github.com/Azure/azure-cli/pull/26685
  - https://github.com/Azure/azure-cli/pull/25370
  - https://github.com/Azure/azure-cli/pull/26923
    - https://github.com/Azure/azure-cli/pull/26991 
    - https://github.com/Azure/azure-cli/pull/27148
    - https://github.com/Azure/azure-cli/pull/27073

**Comment by jiasli** [comment]
`psycopg2` (introduced by #22459) fails to install on Python 3.11:

```
Collecting psycopg2==2.9.3
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ------------------------------------- 380.6/380.6 kB 23.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [23 lines of output]
  running egg_info
  creating C:\Users\jiasli\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info
  writing C:\Users\jiasli\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\PKG-INFO
  writing dependency_links to C:\Users\jiasli\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\dependency_links.txt
  writing top-level names to C:\Users\jiasli\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\top_level.txt
  writing manifest file 'C:\Users\jiasli\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.
```

**Comment by jiasli** [comment]
`psycopg2` (introduced by #22459) fails to install on Python 3.11:

```
Collecting psycopg2==2.9.3
  Downloading psycopg2-2.9.3.tar.gz (380 kB)
     ------------------------------------- 380.6/380.6 kB 23.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [23 lines of output]
  running egg_info
  creating C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info
  writing C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\PKG-INFO
  writing dependency_links to C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\dependency_links.txt
  writing top-level names to C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\top_level.txt
  writing manifest file 'C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-4nrehwws\psycopg2.egg-info\SOURCES.txt'

  Error: pg_config executable not found.

  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:

      python setup.py build_ext --pg-config /path/to/pg_config build ...

  or with the pg_config option in 'setup.cfg'.

  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.

  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).

  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.
```

**Comment by bebound** [comment]
I guess we need to update `psycopg2` to 2.9.5
https://github.com/psycopg/psycopg2/issues/1514

**Comment by bebound** [comment]
`vcrpy` also does not support 3.11, we need to wait for next release.

They've added 3.11 support in this PR: [add python 3.11 support](https://github.com/kevin1024/vcrpy/pull/667)
```
ImportError while importing test module '/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/azure-cli/azure/cli/command_modules/network/tests/latest/test_private_endpoint_commands.py:13: in <module>
    from azure.cli.testsdk import (
src/azure-cli-testsdk/azure/cli/testsdk/__init__.py:6: in <module>
    from .scenario_tests import live_only, record_only, get_sha1_hash
src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/__init__.py:13: in <module>
    from .base import IntegrationTestBase, ReplayableTest, LiveTest
src/azure-cli-testsdk/azure/cli/testsdk/scenario_tests/base.py:14: in <module>
    import vcr
env/lib/python3.11/site-packages/vcr/__init__.py:2: in <module>
    from .config import VCR
env/lib/python3.11/site-packages/vcr/config.py:11: in <module>
    from .cassette import Cassette
env/lib/python3.11/site-packages/vcr/cassette.py:8: in <module>
    import wrapt
env/lib/python3.11/site-packages/wrapt/__init__.py:10: in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
env/lib/python3.11/site-packages/wrapt/decorators.py:34: in <module>
    from inspect import ismethod, isclass, formatargspec
E   ImportError: cannot import name 'formatargspec' from 'inspect' (/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/inspect.py)

```

**Comment by bebound** [comment]
`vcrpy` supports 3.11 in https://github.com/kevin1024/vcrpy/pull/667, but it's dependency `multidict` does not provide wheels for 3.11. Here is the issue [Wheels for CPython 3.11](https://github.com/aio-libs/multidict/issues/778).
```
vcrpy                   Automatically mock your HTTP interactions to simplify and speed up testing
├── PyYAML              YAML parser and emitter for Python
├── six>=1.5            Python 2 and 3 compatibility utilities
├── wrapt               Module for decorators, wrappers and monkey patching.
└── yarl                Yet another URL library
    ├── idna>=2.0       Internationalized Domain Names in Applications (IDNA)
    └── multidict>=4.0  multidict implementation
```

**Comment by mrmuskrat** [comment]
Is there a workaround for users on an operating system with python3.11 preinstalled (like Fedora 37)?

**Comment by mrmuskrat** [comment]
> Is there a workaround for users on an operating system with python3.11 preinstalled (like Fedora 37)?

I did find a workaround for myself this afternoon.

Steps:

1. Remove the azure-cli RPM: `sudo dnf remove azure-cli`
2. Install Python 3.10: `sudo dnf install python3.10`
3. Create a virtual environment for Python: `python3.10 -m venv ~/.venv`
4. Activate the virtual environment: `. ~/.venv/bin/activate`
5. Install the Azure CLI using pip: `pip install azure-cli`

**Comment by jiasli** [comment]
A CVE has been reported with `Program Files (x86)\Microsoft SDKs\Azure\CLI2\python310.dll`: https://github.com/Azure/azure-cli/issues/25246, though I can't see its validity yet. Anyway, let's try to use Python 3.11 if all blockers are now gone.

**Comment by jiasli** [comment]
> PS: This dependency tree is generated with [johnnydep](https://pypi.org/project/johnnydep/)

A more popular tool is `pipdeptree`: https://pypi.org/project/pipdeptree/ 😉

**Comment by peterbax117** [comment]
https://nvd.nist.gov/vuln/detail/CVE-2023-24329

With the new CVE-2023-24329, Program Files (x86)\Microsoft SDKs\Azure\CLI2\python310.dll now shows in security scans and will start to be automatically removed from environments.

![CVE-2023-24329-Scan](https://user-images.githubusercontent.com/28738158/225044605-8fa90fec-b111-45a0-aaab-2defb8be93d2.png)

**Comment by jiasli** [comment]
@peterbax117, it seems the Python community still has some debate on `CVE-2023-24329`: https://github.com/python/cpython/issues/102153

**Comment by peterbax117** [comment]
@jiasli , Thank you for the information and link.  I will follow-up on this with the customer and point them to the Python community.  Appreciate the quick response.

**Comment by jiasli** [comment]
I have contacted Microsoft's internal Python community and got their reply:

> Any risk here would be from people relying on urlparse to implement security measures like site blocking.

So the Python 3.10 itself is safe to use. 

According to [Python's official website](https://www.python.org/downloads/), Python 3.10 is a fully supported version, including `python310.dll`. Therefore, we don't think Azure CLI is affected by CVE-2023-24329.

**Comment by luckman212** [comment]
Today I noticed `azure-cli` is the last remaining tool I have installed via Homebrew that depends on Python3.10. I do hope one day 3.11 is supported.

**Comment by roman-vynar** [comment]
This happens every time! Very annoying!

When the main python was 3.10, it depended from 3.9. 
Now 3.11 vs 3.10. 
Most likely it was the same way a long time ago as well but I can't confirm exactly.

Can we please stop hardcoding python version into this tool?
awscli has never had such issues and it's not different much.

Thank you!

**Comment by luckman212** [comment]
Python 3.12 is now the current version. We never even got 3.11 support! I hope this hardcoded dependency on 2+ year old versions of Python will be solved at some point.

**Comment by provenvelocity** [comment]
FYI some pages still say pyhton 3.11 is supported but extensions do not work.

TASK [devsecops.azure.default : Install install extension] *********************
fatal: [instance]: FAILED! => changed=true
  cmd: az --version | grep 'logicapp' || az extension add --yes --source 'https://aka.ms/logicapp-latest-py2.py3-none-any.whl' --system --upgrade
  delta: '0:00:07.615903'
  end: '2023-10-18 02:34:46.296544'
  msg: non-zero return code
  rc: 1
  start: '2023-10-18 02:34:38.680641'
  stderr: |-
    WARNING: Unable to check if your CLI is up-to-date. Check your internet connection.

    Please let us know how we are doing: https://aka.ms/azureclihats
    and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
    ERROR: The command failed with an unexpected error. Here is the traceback:
    ERROR: argument _subcommand: conflicting subparser: add
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 231, in invoke
        cmd_result = self.invocation.execute(args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 560, in execute
        self.parser.load_command_table(self.commands_loader)
      File "/usr/local/lib/python3.11/site-packages/azure/cli/core/parser.py", line 100, in load_command_table
        command_parser = subparser.add_parser(command_verb,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/argparse.py", line 1185, in add_parser
        raise ArgumentError(self, _('conflicting subparser: %s') % name)
    argparse.ArgumentError: argument _subcommand: conflicting subparser: add
    To open an issue, please run: 'az feedback'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

**Comment by bebound** [comment]
@provenvelocity The PR is merged but we haven't release a new CLI version. 3.11 will be supported in next release.
