### ISSUE TITLE
Improve autocompletion performance

### ISSUE THREAD

**Issue by bebound** [Azure/azure-cli#25107]
## Description
Original issue: https://github.com/Azure/azure-cli/issues/9157
CLI's autocompletion is not as fast as other tools, I create this issue to track the progress.
If you find any command's completion is slow, please report it here and attach the output of `{your_command} --debug` and `az -v`.

## TODO
- [ ] https://github.com/Azure/azure-cli/pull/24765
- [ ] https://github.com/Azure/azure-cli/issues/25106
- [ ] Improve module init speed such as acs, network, serviceconnector, rdbms.

**Comment by yonzhan** [comment]
Improve autocompletion performance

**Comment by BradAF** [comment]
I am experiencing this issue, but I'm not sure how to capture the delay speed specifically of the tab completion, rather than running the command. To be clear, the command itself runs reasonably fast, it's the tab-completion that is very slow.

Example: `az account show` runs in under a second, `az acc<tab>` takes 2 seconds to bring up `az account`.

Output of `az -v`:
> azure-cli                         2.44.1
>
> core                              2.44.1
> telemetry                          1.0.8
>
> Extensions:
> connectedk8s                       1.2.8
> k8s-extension                      1.2.0
> azure-devops                      0.22.0
> ml                                2.12.1
>
> Dependencies:
> msal                              1.20.0
> azure-mgmt-resource             21.1.0b1
>
> Python location '/usr/local/Cellar/azure-cli/2.44.1/libexec/bin/python'
> Extensions directory '/Users/XXXX/.azure/cliextensions'
>
> Python (Darwin) 3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)]
>
> Legal docs and information: aka.ms/AzureCliLegal

**Comment by bebound** [comment]
@BradAF Thank for the report, it should be fixed by #24765
