### ISSUE TITLE
Support Python 3.13

### ISSUE THREAD

**Issue by Goldziher** [Azure/azure-cli#29640]
Python 3.13 is in the works and will be released in the nearish future. It would be great to have it supported. 

## TODOs
- aaz-dev supports 3.13
  - https://github.com/Azure/aaz-dev-tools/pull/495
- azdev supports 3.13
  - https://github.com/Azure/azure-cli-dev-tools/pull/527
- Dependencies are updated to the Python 3.13 compatible version
  - https://github.com/Azure/azure-cli/pull/31822
  - https://github.com/Azure/azure-cli/pull/31823
- CI passes with Python 3.13
  - aaz warning: `FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior`
  - https://github.com/Azure/azure-cli/pull/31895
  - https://github.com/Azure/azure-cli/pull/31928
  - https://github.com/Azure/azure-cli-extensions/pull/9056
- Extension compatible with Python 3.13
  - `webpubsub`: `ModuleNotFoundError: No module named 'cgi'` https://github.com/Azure/azure-cli-extensions/pull/8993 
  - `azure-sphere`: `from pathlib import Path, os` `ImportError: cannot import name 'os' from 'pathlib'` https://github.com/Azure/azure-cli-extensions/pull/9025

**Comment by yonzhan** [comment]
Thank you for opening this issue, we will look into it.

**Comment by Goldziher** [comment]
Thank you! i would like to point out that typing is a major point of improvement for the v3.12 and 3.13. Especially the new generic syntax etc.

**Comment by XhmikosR** [comment]
Any news about this? Fedora Workstation 41 ships with Python 3.13 and there are failures with v2.62.

**Comment by dmilith** [comment]
It's 3.13.1 already, but this still fails like this:

```
ERROR: Ignored the following yanked versions: 0.13.11, 0.13.13, 0.14.1
ERROR: Could not find a version that satisfies the requirement pymsalruntime<0.18,>=0.17; (python_version >= "3.8" and platform_system == "Darwin") and extra == "broker" (from msal[broker]) (from versions: 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.10.0, 0.11.0, 0.11.2, 0.12.4, 0.13.0, 0.13.1, 0.13.2, 0.13.9, 0.13.12, 0.14.0, 0.14.2a1, 0.14.2, 0.15.0a1)
ERROR: No matching distribution found for pymsalruntime<0.18,>=0.17; (python_version >= "3.8" and platform_system == "Darwin") and extra == "broker"
```

**Comment by zippy1981** [comment]
Currently, on Python 3.13.1 on windows it fails for me because it tries to compile `pymsalruntime`. I will get a machine with a C++ compiler and test that.

```
Building wheels for collected packages: pymsalruntime
  Building wheel for pymsalruntime (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pymsalruntime (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\pymsalruntime
      copying pymsalruntime\__init__.py -> build\lib.win-amd64-cpython-313\pymsalruntime
      copying pymsalruntime\PyMsalRuntime.pyi -> build\lib.win-amd64-cpython-313\pymsalruntime
      copying pymsalruntime\msalruntime.dll -> build\lib.win-amd64-cpython-313\pymsalruntime
      running build_ext
      building 'pymsalruntime.pymsalruntime' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymsalruntime
Failed to build pymsalruntime
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pymsalruntime)
```

**Comment by bebound** [comment]
@zippy1981  Compiling wheel is complex on Windows. We'll wait for the `pymsalruntime` release wheel package.

**Comment by sbreit-tomra** [comment]
> Any news about this? Fedora Workstation 41 ships with Python 3.13 and there are failures with v2.62.

Same with Arch, still Python 3.13 related failures in 2.67.0.

**Comment by sodul** [comment]
The pymsalruntime package is owned by Microsoft owned and used to authenticate against Azure. So it is unavoidable.

The bug has been opened on their side since December and it was prioritized last week so it will take a while before a new working release is available.

Now an other issue is that the azure cli requirements might pin to a specific release which means that we would also need azure-cli to accept this future release.

https://github.com/search?q=org%3Aazure+pymsalruntime+&type=code

For example `azure-cli/requirements.py3.windows.txt` has `pymsalruntime==0.16.2` which means that it will prevent the use of the new release when it comes out.

It might be a good idea for Microsoft maintainers of Azure-cli to talk to the Microsoft maintainers of pymsalruntime so that paying Microsoft customers (through Azure bills) can get support sooner.

**Comment by sbreit-tomra** [comment]
With Python 3.13, I get this error: `/opt/azure-cli/lib/python3.13/site-packages/azure/cli/core/aaz/_command.py:135: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior`

I reckon this too is a Python 3.13 related issue, not a different one?

**Comment by sodul** [comment]
@sbreit-tomra You should probably open a new bug to get the new `functools.partial` warning addressed for future compatibility. It should not cause any runtime issues with 3.13, the warning is that the code will break in future versions of python, maybe 3.14, or later.

In a way these warnings are a good thing as it puts pressure on maintainers to future proof code, but at the same time is a lot of noise for the users.

**Comment by mtene** [comment]
I've tried the workaround mentioned in the thread below
https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/823#issuecomment-2887381693

pip install https://github.com/AzureAD/microsoft-authentication-library-for-python/archive/refs/heads/dev.zip

Then retried installing azure-cli, which then succeeded on Python 3.13

**Comment by qris** [comment]
Should be fixed by the [MSAL Python 1.33.0b1 release](https://github.com/AzureAD/microsoft-authentication-library-for-python/pull/827), which is used since [!31563](https://github.com/Azure/azure-cli/pull/31563):

> A byproduct of this is that broker on all platforms will support Python 3.13.

**Comment by franpb90** [comment]
Hi

Are there any updates regarding this upgrade? We're currently receiving critical security alerts due to the Azure CLI, specifically related to CVE-2025-4517.
This vulnerability is affecting our environment, and we're keen to understand if a fix or mitigation is planned soon.

Thanks for your support!

**Comment by bebound** [comment]
@franpb90  CLI is not affected by CVE-2025-4517. We plan to bump to 3.13 in September release to address it.

**Comment by RenSilvaAU** [comment]
@bebound , @zippy1981 ,

The problem is happening in package **aaz-dev**, not in **az-cli.**

az-cli has dependency on aaz-dev for development (not for use), so:


**This command works and the package installs:**
`pip install az-cli`

**This command fails with the error identified:**
`pip install aaz-dev`

We will continue to investigate it.

**Comment by bebound** [comment]
> [@bebound](https://github.com/bebound) , [@zippy1981](https://github.com/zippy1981) ,
> 
> The problem is happening in package **aaz-dev**, not in **az-cli.**
> 
> az-cli has dependency on aaz-dev for development (not for use), so:
> 
> **This command works and the package installs:** `pip install az-cli`
> 
> **This command fails with the error identified:** `pip install aaz-dev`
> 
> We will continue to investigate it.

@kairu-ms for awareness.
At least, `lxml~=4.9.4` is not compatible with python 3.13.

**Comment by RenSilvaAU** [comment]
> > [@bebound](https://github.com/bebound) , [@zippy1981](https://github.com/zippy1981) ,
> > The problem is happening in package **aaz-dev**, not in **az-cli.**
> > az-cli has dependency on aaz-dev for development (not for use), so:
> > **This command works and the package installs:** `pip install az-cli`
> > **This command fails with the error identified:** `pip install aaz-dev`
> > We will continue to investigate it.
> 
> [@kairu-ms](https://github.com/kairu-ms) for awareness. At least, `lxml~=4.9.4` is not compatible with python 3.13.

@bebound , @kairu-ms ,

When using `lxml>=5.0.0`, the package builds under python 3.13.x - I am now testing for compatibility with lower Python versions

**Comment by RenSilvaAU** [comment]
Built and tested aaz-dev with python 3.8 ~ 3.13 in ubuntu, windows and Mac OS. 

Pull request: https://github.com/Azure/aaz-dev-tools/pull/495

**Comment by RenSilvaAU** [comment]
Since the latest upgrade of azdev, the following works under Windows, Mac & Ubuntu, with Python 3.13.5:

- [x] pip install azure-cli 
- [x] pip install azure-cli --only-binary=:all:

but still fails
- [ ] pip install aaz-dev
- [ ] pip install aaz-dev --only-binary=:all:

Working on the release of new aaz-dev-tools

**Comment by RenSilvaAU** [comment]
Since the latest upgrade of azdev, and aaz-dev tools, the following works under Mac & Ubuntu, with Python 3.13.6:

- [x] pip install azure-cli 
- [x] pip install azure-cli --only-binary=:all:
- [x] pip install aaz-dev
- [x] pip install aaz-dev --only-binary=:all:

**Comment by RenSilvaAU** [comment]
I am now testing Windows

**Comment by RenSilvaAU** [comment]
Since the latest upgrade of azdev, and aaz-dev tools, the following works under Windows, with Python 3.13.5:


- [x] pip install azure-cli
- [x] pip install azure-cli --only-binary=:all:
- [x] pip install aaz-dev
- [x] pip install aaz-dev --only-binary=:all:

**Comment by RenSilvaAU** [comment]
> With Python 3.13, I get this error: `/opt/azure-cli/lib/python3.13/site-packages/azure/cli/core/aaz/_command.py:135: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior`
> 
> I reckon this too is a Python 3.13 related issue, not a different one?

@sbreit-tomra ,

Could you share the steps you used to trigger this?

**Comment by rogeruiz** [comment]
I get the error above on python 3.13.4 using az 2.74.0 whenever I run the `az container show ...` command. It does not prevent the command from running properly.
