### ISSUE TITLE
[Test] Boost Application Gateway subresource test coverage

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#3941]
Add tests for the following AppGateway sub-resource commands:

- [x] address-pool (PR #4137)
- [ ] auth-cert
- [x] frontend-ip (PR #4137)
- [x] frontend-port (PR #4137)
- [x] http-listener (PR #4137)
- [x] http-settings (PR #4137)
- [X] probe (PR #4137)
- [x] redirect-config (PR #4069)
- [x] rule (PR #4137)
- [ ] ssl-cert
- [X] ssl-policy
- [ ] url-path-map
- [ ] url-path-map rule
- [X] waf-config
