### ISSUE TITLE
Application Gateway support for new features

### ISSUE THREAD

**Issue by amitsriva** [Azure/azure-cli#7528]
- [x] Zone support for `application-gateway create` (#7789)
- [x] Trusted Root Certificates (new child resource of appgw) (#7789)
- [x] Autoscale Configuration (new property of appgw) (#7789)
- [x] WAF configurability (#7789)
- [x] WAF exclusion list (#7920)
- [x] Custom error pages (#7789)

**Comment by tjprescott** [comment]
Moving to sprint 50 for the remaining ask.
