### ISSUE TITLE
[Network] Update Commands not at parity with Xplat

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli#818]
The vast majority of the networking `update` commands rely on the generic update (`add, set, remove`) to achieve their functionality. However, this means that when compared to Xplat, they are missing several convenience options and thus, while at technical parity, might not be considered at "UX parity" (if that's a thing) by users and/or service teams. The following commands have this issue:
- [x] public-ip (PR #1461)
- [x] traffic-manager profile (PR #1511)
- [x] traffic-manager endpoint (PR #1511)
- [x] route-table route (PR #1693)
- [x] local-gateway (PR #1456 puts this ahead of Xplat and on parity with Powershell)
- [x] vpn-gateway (PR #1474)
- [x] vpn-connection (PR #1539)
- [x] application-gateway (PR #1606)
- [x] express-route circuit (PR #1694)
- [x] express-route peering (PR #1694)
- [x] dns record-set (PR #1592)

**Comment by mayurid** [comment]
@jasonrshaver: Something to discuss with the Network team on.

**Comment by tjprescott** [comment]
Continuing this into Sprint 9.
